version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: root
      POSTGRES_DB: db01
      PGDATA: /home/eugene/postgres/data
      POSTGRES_HOST: 127.0.0.1

    ports:
      - $DB_PORT:5432

  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: root
      POSTGRES_DB: db01
      POSTGRES_HOST: 127.0.0.1

    ports:
      - $DB_TEST_PORT:5432
