version: '3.1'
services:

  web:
    image: cr.yandex/crpeam5f0o0iuj2u3vtj/server:server
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic revision --autogenerate; alembic upgrade head; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 80:8000

    environment:
      - DATABASE_LINK=postgresql://root:123123@db:5432/db01
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data2/
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    expose:
      - 5432


volumes:
  postgres_data:
