version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /home/idfilatov/postgres/data
      POSTGRES_HOST: ${POSTGRES_HOST}

    ports:
      - '5432:5432'
