version: '3.1'
services:
  db-test:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data2/
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: root
      POSTGRES_DB: test-postgres
#      PGDATA: /var/lib/postgresql/data/
#      POSTGRES_HOST: ${POSTGRES_HOST}

    ports:
      - "5433:5433"


volumes:
  postgres_data:
