version: '3.1'
services:
  web:
    build: .
    command: bash -c "alembic revision --autogenerate && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 80:8000
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
#      PGDATA: /var/lib/postgresql/data/
#      POSTGRES_HOST: ${POSTGRES_HOST}

    ports:
      - "5432:5432"


volumes:
  postgres_data:
