"""rename hash

Revision ID: 730dc42314b3
Revises: fe7d195bcc7c
Create Date: 2023-01-20 15:51:12.974544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730dc42314b3'
down_revision = 'fe7d195bcc7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['id'])
    op.create_unique_constraint(None, 'hashrate', ['id'])
    op.create_unique_constraint(None, 'permission', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'permission', type_='unique')
    op.drop_constraint(None, 'hashrate', type_='unique')
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
