"""Hash float

Revision ID: 7dfb61f82943
Revises: ff5bf951e0aa
Create Date: 2023-01-19 17:29:49.410194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfb61f82943'
down_revision = 'ff5bf951e0aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['id'])
    op.create_unique_constraint(None, 'hash', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hash', type_='unique')
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
