# This is a basic workflow to help you get started with Actions

name: pipeline
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
#      - uses: isbang/compose-action@v1.4.1
#        with:
#          compose-file: "docker-compose.yaml"
#          down-flags: "--volumes"
#          services: |
#            db

      - name: start docker
        run: docker compose up -d

      - name: install depends
        run: pip install -r requirements.txt

#      - name: alembic
#        run: |
#          alembic revision --autogenerate
#          alembic upgrade head

#      - name: Docker Build
#        run: docker compose up -d --build

      - name: Start test
        run: pytest

  deploy:
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker build
        run: docker build --tag ${{ secrets.DOCKER_LOGIN }}/back:prod .

      - name: docker login
        run: docker login --username '${{ secrets.DOCKER_LOGIN }}' --password '${{ secrets.DOCKER_PASSWORD }}'
